name: node.js CI

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfixes'
      - 'release/**'
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - strategy:
          matrix:
            node-version: [18.x]

      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Generate Environment Variables File for Production
        env:
          REACT_APP_DOMAIN: ${{ secrets.your_key }}
        run: |
          echo "your_key=$your_key" >> .env

      - name: Install Dependencies
      - run: yarn --immutable --immutable-cache --check-cache

      - name: Lint Test
      - run: yarn lint

      - name: Unit Test
      - run: yarn test

      - name: Build Packages
        run: yarn build
